# Generated by Django 3.2.16 on 2023-02-23 07:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import usermanager.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=200, null=True)),
                ('condition', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('invalidity_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=False, max_length=100, null=True)),
                ('name_local', models.CharField(blank=True, default=False, max_length=100, null=True)),
                ('short_name', models.CharField(blank=True, default=False, max_length=3, null=True)),
                ('code', models.IntegerField()),
                ('border_with', models.CharField(blank=True, default=False, max_length=250, null=True)),
                ('border_length', models.IntegerField()),
                ('hotline', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('local_name', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=usermanager.models.upload_logo_company)),
                ('vat_number', models.CharField(blank=True, max_length=100, null=True)),
                ('tel_number', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('founded', models.DateField()),
                ('founder', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_local', models.CharField(blank=True, max_length=100, null=True)),
                ('short_name', models.CharField(blank=True, max_length=3, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('primary_language', models.CharField(blank=True, max_length=50, null=True)),
                ('alt_languages', models.CharField(blank=True, max_length=250, null=True)),
                ('border_with', models.CharField(blank=True, max_length=250, null=True)),
                ('border_length', models.IntegerField(blank=True, null=True)),
                ('landmark', models.IntegerField(blank=True, null=True)),
                ('leader_name', models.CharField(blank=True, max_length=100, null=True)),
                ('leader_position', models.CharField(blank=True, max_length=100, null=True)),
                ('born_year', models.IntegerField(blank=True, null=True)),
                ('is_before_chris', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kh', models.CharField(blank=True, max_length=100, null=True)),
                ('customerId', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(default='Male', max_length=200, null=True)),
                ('birthdate', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to=usermanager.models.upload_customer_image)),
                ('relationship_status', models.BooleanField(blank=True, null=True)),
                ('is_black_list', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name_spouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanager.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('loan_cycle_type', models.CharField(choices=[('day', 'day'), ('week', 'week'), ('month', 'month'), ('quarter', 'quarter'), ('semester', 'semester'), ('year', 'year')], max_length=8)),
                ('number_of_cycle', models.PositiveIntegerField()),
                ('interest_rate_per_cycle', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('loan_date', models.DateField()),
                ('is_set_first_payment_date', models.BooleanField(default=False)),
                ('first_payment_date', models.DateField(blank=True, null=True)),
                ('rate_calculate_method', models.CharField(choices=[('fixed flat', 'fixed flat'), ('Equal Installments', 'Equal Installments'), ('fixed rate', 'fixed rate')], max_length=18)),
                ('payment_schedule', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanager.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=False, max_length=100, null=True)),
                ('name_local', models.CharField(blank=True, default=False, max_length=100, null=True)),
                ('short_name', models.CharField(blank=True, default=False, max_length=3, null=True)),
                ('code', models.IntegerField()),
                ('border_with', models.CharField(blank=True, default=False, max_length=250, null=True)),
                ('border_length', models.IntegerField()),
                ('hotline', models.IntegerField()),
                ('commune_id', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanager.commune')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_local', models.CharField(blank=True, max_length=100, null=True)),
                ('short_name', models.CharField(blank=True, max_length=3, null=True)),
                ('code', models.IntegerField()),
                ('border_with', models.CharField(blank=True, default=False, max_length=250, null=True)),
                ('border_length', models.IntegerField()),
                ('leader', models.CharField(blank=True, max_length=3, null=True)),
                ('hotline', models.IntegerField()),
                ('country_id', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanager.country')),
            ],
        ),
        migrations.CreateModel(
            name='Payback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('principle_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('due_date', models.DateField()),
                ('pay_date', models.DateField()),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanager.loan')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=usermanager.models.owner_logo)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanPaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_for_due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('pay_with', models.CharField(max_length=20)),
                ('payer', models.CharField(max_length=20)),
                ('is_penalty', models.BooleanField(default=False)),
                ('number_of_day', models.PositiveIntegerField(blank=True, null=True)),
                ('action_date', models.DateField()),
                ('penalty_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanager.loan')),
            ],
        ),
        migrations.CreateModel(
            name='ImageCollateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=usermanager.models.upload_customer_image)),
                ('mortgage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanager.collateral')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_local', models.CharField(blank=True, max_length=100, null=True)),
                ('short_name', models.CharField(blank=True, max_length=3, null=True)),
                ('code', models.IntegerField()),
                ('border_with', models.CharField(blank=True, default=False, max_length=250, null=True)),
                ('border_length', models.IntegerField()),
                ('hotline', models.IntegerField()),
                ('province_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanager.province')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, default=False, max_length=100, null=True)),
                ('house_number', models.CharField(blank=True, default=False, max_length=100, null=True)),
                ('location', models.CharField(blank=True, default=False, max_length=50, null=True)),
                ('commune', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanager.commune')),
                ('customer', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanager.customer')),
                ('district', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanager.district')),
                ('province', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanager.province')),
                ('village', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanager.village')),
            ],
            options={
                'verbose_name_plural': 'Customer Shipping Addresses',
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=False, max_length=50, null=True)),
                ('street', models.CharField(blank=True, default=False, max_length=100, null=True)),
                ('house_number', models.CharField(blank=True, default=False, max_length=100, null=True)),
                ('location', models.CharField(blank=True, default=False, max_length=50, null=True)),
                ('commune', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanager.commune')),
                ('country', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanager.country')),
                ('customer', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanager.customer')),
                ('district', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanager.district')),
                ('province', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanager.province')),
                ('village', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanager.village')),
            ],
            options={
                'verbose_name_plural': 'Customer Addresses',
            },
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, default=False, max_length=100, null=True)),
                ('house_number', models.CharField(blank=True, default=False, max_length=100, null=True)),
                ('is_head_office', models.BooleanField(blank=True, default=False, null=True)),
                ('location', models.CharField(blank=True, default=False, max_length=50, null=True)),
                ('commune', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanager.commune')),
                ('company', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanager.company')),
                ('district', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanager.district')),
                ('province', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanager.province')),
                ('village', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanager.village')),
            ],
            options={
                'verbose_name_plural': 'Company Addresses',
            },
        ),
        migrations.AddField(
            model_name='commune',
            name='district_id',
            field=models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanager.district'),
        ),
        migrations.AddField(
            model_name='collateral',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanager.loan'),
        ),
        migrations.CreateModel(
            name='AmortizationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('interest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanager.loan')),
            ],
        ),
    ]
