# Generated by Django 3.2.16 on 2023-02-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_number_id',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
