# Generated by Django 3.2.16 on 2023-02-27 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0003_payback_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collateral',
            name='cus_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usermanager.customer'),
        ),
    ]
