# Generated by Django 3.2.16 on 2023-02-28 12:22

from django.db import migrations, models
import usermanager.models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0005_rename_mortgage_imagecollateral_collateral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecollateral',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=usermanager.models.upload_collateral_image),
        ),
    ]
