# Generated by Django 3.2.16 on 2023-03-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0006_auto_20230301_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
