# Generated by Django 3.2.16 on 2023-03-01 08:17

from django.db import migrations, models
import django.db.models.deletion
import usermanager.models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0007_alter_idcard_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usermanager.customer'),
        ),
        migrations.AlterField(
            model_name='imageidcard',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=usermanager.models.upload_id_image),
        ),
    ]
