# Generated by Django 3.2.16 on 2023-03-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0009_remove_idcard_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='laon_status',
            field=models.CharField(blank=True, choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Loose', 'Loose')], default='Ongoing', max_length=20),
        ),
    ]
