# Generated by Django 3.2.16 on 2023-03-02 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0006_alter_imagecollateral_image'),
        ('usermanager', '0011_alter_idcard_card_number'),
    ]

    operations = [
    ]
