# Generated by Django 3.2.16 on 2023-03-03 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0012_activity'),
        ('usermanager', '0012_merge_20230302_1956'),
    ]

    operations = [
    ]
