# Generated by Django 3.2.16 on 2023-03-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0012_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='table',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='table_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
