# Generated by Django 3.2.16 on 2023-03-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0013_auto_20230304_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='update_on',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
