# Generated by Django 3.2.16 on 2023-03-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0015_merge_20230304_1728'),
        ('usermanager', '0015_merge_20230304_1743'),
    ]

    operations = [
    ]
