# Generated by Django 3.2.16 on 2023-03-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0017_auto_20230306_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='laon_status',
            field=models.CharField(blank=True, choices=[('on going', 'on going'), ('completed', 'completed'), ('lost', 'lost')], default='on going', max_length=20),
        ),
    ]
