# Generated by Django 3.2.16 on 2023-03-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0018_auto_20230317_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='payback',
            name='full_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
