# Generated by Django 3.2.16 on 2023-03-18 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0018_alter_loan_laon_status'),
        ('usermanager', '0018_auto_20230317_1710'),
    ]

    operations = [
    ]
