# Generated by Django 3.2.16 on 2023-03-20 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0019_merge_20230319_0655'),
        ('usermanager', '0019_payback_full_paid'),
    ]

    operations = [
    ]
