# Generated by Django 3.2.16 on 2023-03-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0020_merge_0019_merge_20230319_0655_0019_payback_full_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='laon_status',
        ),
        migrations.AddField(
            model_name='loan',
            name='full_off_from',
            field=models.BigIntegerField(blank=True, default='3', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_status',
            field=models.CharField(blank=True, choices=[('on going', 'on going'), ('completed', 'completed'), ('lost', 'lost')], default='on going', max_length=20),
        ),
    ]
