# Generated by Django 3.2.16 on 2023-03-20 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0022_alter_loan_full_off_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payback',
            name='status',
        ),
    ]
