# Generated by Django 3.2.16 on 2023-03-24 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0023_remove_payback_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_account_number', models.BigIntegerField()),
                ('bank_account_currency', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanager.company')),
            ],
        ),
    ]
