# Generated by Django 3.2.16 on 2023-03-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0024_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
