# Generated by Django 3.2.16 on 2023-03-24 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0025_company_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaddress',
            name='country',
            field=models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanager.country'),
        ),
    ]
