# Generated by Django 3.2.16 on 2023-04-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0027_auto_20230331_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='payback',
            name='is_full_paid',
            field=models.BooleanField(default=False),
        ),
    ]
