# Generated by Django 3.2.16 on 2023-04-08 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0028_payback_is_full_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collateral',
            old_name='invalidity_date',
            new_name='expired_date',
        ),
        migrations.RemoveField(
            model_name='collateral',
            name='loan',
        ),
        migrations.AddField(
            model_name='collateral',
            name='collateral_num',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='collateral',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('refunded', 'refunded'), ('expired', 'expired'), ('sold', 'sold')], default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='collateral',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usermanager.collateral'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collateral',
            name='cus_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanager.customer'),
        ),
    ]
