# Generated by Django 3.2.16 on 2023-04-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0029_auto_20230408_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collateral',
            name='expired_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
