# Generated by Django 3.2.16 on 2023-04-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0030_alter_collateral_expired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collateral',
            name='collateral_num',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
