# Generated by Django 3.2.16 on 2023-04-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0031_alter_collateral_collateral_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='collateral',
        ),
        migrations.AddField(
            model_name='loan',
            name='collateral',
            field=models.ManyToManyField(to='usermanager.Collateral'),
        ),
    ]
