# Generated by Django 3.2.16 on 2023-04-08 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0032_auto_20230408_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='collateral',
        ),
        migrations.AddField(
            model_name='collateral',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanager.loan'),
        ),
    ]
