# Generated by Django 3.2.16 on 2023-04-10 08:03

from django.db import migrations, models
import usermanager.models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0033_auto_20230408_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='payback',
            name='attached_file',
            field=models.ImageField(blank=True, null=True, upload_to=usermanager.models.upload_collateral_image),
        ),
    ]
