# Generated by Django 3.2.16 on 2023-04-10 10:18

from django.db import migrations, models
import django.db.models.deletion
import usermanager.models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0034_payback_attached_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paw_status', models.CharField(blank=True, choices=[('active', 'active'), ('refunded', 'refunded'), ('expired', 'expired'), ('sold', 'sold')], default='active', max_length=20)),
                ('paw_pay_method', models.CharField(blank=True, choices=[('day', 'day'), ('week', 'week'), ('month', 'month'), ('year', 'year')], default='day', max_length=20)),
                ('paw_name', models.CharField(blank=True, max_length=30)),
                ('paw_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('paw_type', models.CharField(blank=True, max_length=200)),
                ('is_percentage', models.BooleanField(default=False)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('date_paw', models.DateField()),
                ('date_expired_paw', models.DateField()),
                ('is_image', models.BooleanField(default=False)),
                ('paw_image', models.ImageField(blank=True, upload_to=usermanager.models.upload_collateral_image)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanager.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PawPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('date_pay', models.DateField()),
                ('attached_file', models.ImageField(blank=True, upload_to=usermanager.models.upload_collateral_image)),
                ('paw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanager.paw')),
            ],
        ),
    ]
