# Generated by Django 3.2.16 on 2023-04-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0036_auto_20230410_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='mr',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
