# Generated by Django 3.2.16 on 2023-04-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0037_company_mr'),
    ]

    operations = [
        migrations.AddField(
            model_name='paw',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
