# Generated by Django 4.2 on 2023-04-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0038_paw_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='main_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
