# Generated by Django 4.2 on 2023-04-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0039_company_main_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='main_currency',
            field=models.CharField(blank=True, default='$', max_length=3, null=True),
        ),
    ]
