# Generated by Django 4.2 on 2023-04-27 09:08

from django.db import migrations, models
import django.db.models.deletion
import usermanager.models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0040_alter_company_main_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='paw',
            name='is_principle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paw',
            name='paw_period_principle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paw',
            name='paw_principle_cycle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paw',
            name='paw_image',
            field=models.ImageField(blank=True, upload_to=usermanager.models.upload_customer_image),
        ),
        migrations.CreateModel(
            name='pawImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=usermanager.models.upload_customer_image)),
                ('crate_at', models.DateTimeField(auto_now_add=True)),
                ('paw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanager.paw')),
            ],
        ),
    ]
