# Generated by Django 4.2 on 2023-04-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0041_paw_is_principle_paw_paw_period_principle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pawpay',
            name='pay_principle',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
