# Generated by Django 4.2 on 2023-04-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0042_pawpay_pay_principle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pawpay',
            name='pay_principle',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
        ),
    ]
