# Generated by Django 4.2 on 2023-05-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0043_alter_pawpay_pay_principle'),
    ]

    operations = [
        migrations.AddField(
            model_name='pawpay',
            name='remaining',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
        ),
    ]
