# Generated by Django 4.2 on 2023-05-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0045_remove_paw_is_principle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paw',
            name='date_expired_paw',
            field=models.DateField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pawborrow',
            name='date_borrow',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='pawborrow',
            name='date_expired_borrow',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='pawborrow',
            name='is_principle',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
