# Generated by Django 4.2 on 2023-05-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0046_alter_paw_date_expired_paw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pawborrow',
            name='date_expired_paw_borrow',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paw',
            name='date_expired_paw',
            field=models.DateField(blank=True, null=True),
        ),
    ]
