# Generated by Django 4.2 on 2023-05-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0047_pawborrow_date_expired_paw_borrow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pawborrow',
            name='date_expired_paw_borrow',
        ),
        migrations.AlterField(
            model_name='pawborrow',
            name='date_borrow',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pawborrow',
            name='date_expired_borrow',
            field=models.DateField(blank=True, null=True),
        ),
    ]
