# Generated by Django 4.2 on 2023-05-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0048_remove_pawborrow_date_expired_paw_borrow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paw',
            name='paw_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
