# Generated by Django 4.2 on 2023-05-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0049_alter_paw_paw_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paw',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
