# Generated by Django 4.2 on 2023-05-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0050_alter_paw_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paw',
            name='date_paw',
            field=models.DateField(blank=True, null=True),
        ),
    ]
