# Generated by Django 4.2 on 2023-05-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0051_alter_paw_date_paw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paw',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='pawborrow',
            name='paw_borrow_period_principle',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pawborrow',
            name='paw_borrow_principle_cycle',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pawborrow',
            name='paw_borrow_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
        ),
    ]
