# Generated by Django 4.2 on 2023-05-13 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0052_alter_paw_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowpayback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('pay_principle', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('date_payback', models.DateField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('borrow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanager.pawborrow')),
            ],
        ),
    ]
