# Generated by Django 4.2 on 2023-05-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0053_borrowpayback'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='text_loan_amount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
