# Generated by Django 4.2 on 2023-05-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0054_loan_text_loan_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowpayback',
            name='total_pay',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
