# Generated by Django 4.2 on 2023-05-26 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0056_department_employeedetail_position_employeelist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='department',
        ),
    ]
