# Generated by Django 4.2 on 2023-05-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0057_remove_position_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='usersetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sidebar', models.BooleanField(default=True)),
                ('is_navbar', models.BooleanField(default=False)),
            ],
        ),
    ]
