# Generated by Django 4.2 on 2023-05-29 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0060_remove_usersetting_user_usersetting_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersetting',
            name='is_navbar',
        ),
    ]
