# Generated by Django 4.2 on 2023-05-31 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0062_rename_pay_value_pawpay_pay_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_invest', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('name_investor', models.CharField(blank=True, max_length=30)),
                ('position_investor', models.CharField(blank=True, max_length=20)),
                ('descriptions', models.TextField(blank=True)),
                ('join', models.DateTimeField(blank=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanager.company')),
            ],
        ),
    ]
